version: "3.8"

services:
  cintelink_app:
    build:
      context: .
      dockerfile: ./compose/local/backend/Dockerfile
    image: cintelink_app_image:latest
    container_name: cintelink_app
    command: /start
    volumes:
      - .:/src
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: debezium/postgres:16-alpine
    restart: always
    volumes:
      - cintelink_db_data://var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - 5432:5432

volumes:
  cintelink_db_data:
