#!/bin/sh

database_ready() {
python << END
import sys
import psycopg2

try:
    psycopg2.connect(database="${POSTGRES_DB}",
                      user="${POSTGRES_USER}",
                      password="${POSTGRES_PASSWORD}",
                      host="${POSTGRES_HOST}",
                      port="${POSTGRES_PORT}")
except Exception as e:
    print(f'{e}')
    sys.exit(-1)
sys.exit(0)
END
}

until database_ready; do
  >&2 echo 'Waiting for Postgres to become available...'
  sleep 5
done
>&2 echo 'Postgres is available'

alembic upgrade head

while ! curl -sSf "$DEBEZIUM_URL:8083" >/dev/null; do
    echo "Esperando a que "$DEBEZIUM_URL" esté disponible..."
    sleep 5
done

curl -i -X POST -H "Accept:application/json" -H "Content-Type:application/json" "$DEBEZIUM_URL:8083/connectors/" --data "@debezium.json"
>&2 echo 'Debezium is available'

sleep 10

uvicorn src.main:app --host 0.0.0.0 --reload
