#!/bin/bash

tr -d '\r' < /start > /start.tmp
mv /start.tmp /start

wait-for-it -t 0 kafka:9092
wait-for-it -t 0 schema-registry:8085

curl -i -X POST -H 'Accept: application/json' -H 'Content-Type: application/json' \
    "$DEBEZIUM_URL/connectors/" --data "@debezium.json"

kafkacat -b kafka:9092 -C -s key=s -s value=avro -r http://schema-registry:8085 -t postgres.public.notification
